version: "3.2"
services:
  rabbitmq:
    image: rabbitmq
    container_name: "obelisk-rabbitmq"
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./log:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
