# Configuration of the public entry point
net:
  port: 8346

# Configuration of the service registry
registry:
  server:
    # Can either be AMQP or HTTP. AMQP also needs the keys host, port, user and pass, while HTTP only needs port
    type: AMQP
    host: "localhost"
    port: 5672
    user: "gateway"
    pass: ""

# Authentication endpoint specs; The authentication service is responsible for creating the route
authentication:
  endpoint: "/authenticate"

# Authorization endpoint specs; The authorization service is responsible for creating the route
authorization:
  endpoint: "/authorize"
