name: Build Shelly

on:
  push:
    branches:
      - "development"
    paths:
      - "Shelly"
      - "obelisk-commons"
  pull_request:
    branches:
      - "development"
    paths:
      - "Shelly"
      - "obelisk-commons"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file Shelly/pom.xml
